2025-05-22 20:39:31,106 INFO: Microblog startup [in F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\flaskapp\__init__.py:72]
2025-05-22 20:39:53,462 ERROR: Exception on /edit_profile [POST] [in F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\flaskapp\routes.py", line 101, in edit_profile
    db.session.commit()
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\orm\scoping.py", line 599, in commit
    return self._proxied.commit()
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\orm\session.py", line 4489, in _flush
    transaction.rollback(_capture_exception=True)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\orm\persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\orm\persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "F:\NIKHIL INVENTORY\PROGRAMMING AND PROJECTS\python practice\microblog\microblogvenv\lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('susan', 'Hello from John', 5)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
